### ISSUE TITLE
Wagtail userbar update

### ISSUE THREAD

**Issue by mr-winter** [springload/wagtail#3]
Hey @jordij @tacitus @JoshBarr 
I've been updating the Wagtail userbar, removing the iframe and updating styles. 
Could either of you guys please have a look at [the feature/userbar-inline branch](https://github.com/springload/wagtail/tree/feature/userbar-inline) and confirm that especially the changes I made to [wagtailuserbar.py](https://github.com/springload/wagtail/blob/feature/userbar-inline/wagtail/wagtailadmin/templatetags/wagtailuserbar.py) are all sweet.

**Comment by jordij** [comment]
Looks good to me except the imports. Instead of using `\` better something like:

```
from Tkinter import (Tk, Frame, Button, Entry, Canvas, Text,
    LEFT, DISABLED, NORMAL, RIDGE, END)
```
